// Generated by CoffeeScript 1.6.3
define(["CoordinateSystem"], function(CoordinateSystem) {
  var Card;
  Card = (function() {
    function Card(relativeToCS, ownCS) {
      this.relativeToCS = relativeToCS != null ? relativeToCS : new CoordinateSystem;
      this.ownCS = ownCS != null ? ownCS : new CoordinateSystem;
    }

    Card.prototype.matrix3d = function() {
      return this.ownCS.matrix3d.multiply(this.relativeToCS.matrix3d);
    };

    return Card;

  })();
  return Card;
});
