// Generated by CoffeeScript 1.6.3
define([], function() {
  var CoordinateSystem;
  CoordinateSystem = (function() {
    function CoordinateSystem() {}

    CoordinateSystem.prototype.matrix3d = new WebKitCSSMatrix();

    CoordinateSystem.prototype.webkitTransformOrigin = null;

    return CoordinateSystem;

  })();
  return CoordinateSystem;
});
