// Generated by CoffeeScript 1.6.3
define(["moment", "d3", "jquery-private", "Card", "CoordinateSystem"], function(moment, d3, $, Card, CoordinateSystem) {
  var cards, draw, table, viewport;
  table = new Card;
  cards = [new Card(table.ownCS), new Card(table.ownCS), new Card(table.ownCS)];
  table.ownCS.matrix3d = table.ownCS.matrix3d.rotate(45, 0, 0);
  viewport = d3.select(".viewport");
  draw = function() {
    var d3cards, d3table, height, width;
    d3table = viewport.selectAll(".table").data([table]);
    d3table.enter().append("div").attr("class", "table").style("-webkit-transform-origin", "500px 500px");
    d3table.style("-webkit-transform", function(d) {
      return d.matrix3d();
    });
    width = $(".table").width();
    height = $(".table").height();
    d3cards = viewport.selectAll(".card").data(cards);
    d3cards.enter().append("div").attr("class", "card").style('left', function(d, i) {
      return (i * 110) + "px";
    });
    return d3cards.style("-webkit-transform-origin", function(d) {
      var position;
      position = $(this).position();
      console.log(this, position);
      return (500 - position.left) + "px " + (500 - position.top) + "px ";
    }).style("-webkit-transform", function(d) {
      return d.matrix3d();
    });
  };
  window.yo = {
    table: table,
    cards: cards,
    draw: draw,
    CoordinateSystem: CoordinateSystem,
    do1: function() {
      yo.table.ownCS.matrix3d = new WebKitCSSMatrix();
      return draw();
    },
    do2: function() {
      yo.cards[0].relativeToCS = new CoordinateSystem();
      return draw();
    },
    do3: function() {
      yo.table.ownCS.matrix3d = new WebKitCSSMatrix().rotate(45, 0, 0);
      return draw();
    }
  };
  window.$ = $;
  return draw();
});
